<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/vcard_attachments/localization/<lang>.inc                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 | Copyright (C) 2018, Louis-Philippe Véronneau                          |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/
$labels['addvcardmsg'] = 'Ajouter la vCard au carnet d\'adresses';
$labels['vcardsavefailed'] = 'Impossible d\'enregistrer la vCard';
$labels['attachvcard'] = 'Joindre la vCard';
$labels['vcard'] = 'vCard';
?>
