<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/subscriptions_option/localization/<lang>.inc                  |
 |                                                                       |
 | Localization file of the Roundcube Webmail Subscriptions plugin       |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 | Copyright (C) 2018, Louis-Philippe Véronneau                          |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/
$labels['useimapsubscriptions']  = 'Utiliser les abonnements IMAP';
?>
