<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail New User Dialog plugin     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 | Copyright (C) 2018-2019, Louis-Philippe Véronneau                     |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

*/

$labels['identitydialogtitle'] = 'Veuillez saisir votre identité d’expéditrice ou d’expéditeur';
$labels['identitydialoghint'] = 'Ce champ n’apparaît que lors de la première connexion.';
